package pms.core

import pms.effects._
import pms.effects.implicits._

/**
  *
  * @author Lorand Szakacs, https://github.com/lorandszakacs
  * @since 20 Jun 2018
  *
  */
object Email {

  def apply(em: String): Attempt[Email] =
    if (!em.contains("@"))
      Attempt.raiseError(Fail.invalid("Email must contain: @"))
    else
      Attempt.pure(new Email(em))

}

final class Email private (val plainTextEmail: String) {

  //generated by IntelliJ
  override def equals(other: Any): Boolean = other match {
    case that: Email =>
      plainTextEmail == that.plainTextEmail
    case _ => false
  }

  //generated by IntelliJ
  override def hashCode(): Int =
    31 * plainTextEmail.hashCode
}
