package pms.core

import busymachines.core._
import pms.effects._

/**
  *
  * @author Lorand Szakacs, https://github.com/lorandszakacs
  * @since 20 Jun 2018
  *
  */
object Email {

  def apply(em: String): Result[Email] =
    if (!em.contains("@"))
      Result.fail(InvalidInputFailure("Email must contain: @"))
    else
      Result.pure(new Email(em))

}

final class Email private (val plainTextEmail: String) {

  //generated by IntelliJ
  override def equals(other: Any): Boolean = other match {
    case that: Email =>
      plainTextEmail == that.plainTextEmail
    case _ => false
  }

  //generated by IntelliJ
  override def hashCode(): Int =
    31 * plainTextEmail.hashCode
}
